// generated by @better-translate/cli
export const es = {
  meta: {
    defaultTitle: "Jorge Alvarenga — Desarrollador Full-Stack de Productos",
    defaultDescription: "Desarrollador full-stack de productos construyendo apps web rápidas y confiables con React, Next.js, Astro y TypeScript. Escribo sobre productos e ingeniería.",
  },
  header: {
    homeLabel: "r1go.dev",
    projects: "Proyectos",
    blog: "Blog",
    toggleTheme: "Cambiar tema",
    languageSwitcher: "Cambiador de idioma",
  },
  hero: {
    goBack: "Volver atrás",
  },
  footer: {
    copyright: "todos los derechos reservados © 2026 Jorge Alvarenga",
  },
  sections: {
    projects: "Proyectos",
    posts: "Publicaciones",
  },
  actions: {
    readMore: "Leer más",
    checkMyProjects: "Ver mis proyectos",
    seeMyPosts: "Ver mis publicaciones",
  },
  social: {
    email: "Correo",
  },
  home: {
    heroTitle: "Jorge Alvarenga",
    heroDescription: "Desarrollador Full-Stack & de Productos construyendo herramientas que resuelven problemas reales.",
    intro: "Construyo cosas que necesito, y si son lo suficientemente buenas, las comparto con todos. Con más de 5 años de experiencia en desarrollo frontend y backend, trabajando con diversas tecnologías y frameworks, me enfoco en construir experiencias de usuario performantes y hermosas.",
    currentlyWorkingPrefix: "Actualmente trabajando en",
    currentlyWorkingSuffix: "trabajando como Frontend Engineer con React, Next.js y TypeScript.",
  },
  about: {
    metaTitle: "Sobre mí",
    metaDescription: "Desarrollador full-stack & creador creativo",
    heroTitle: "Sobre mí",
    heroDescription: "Desarrollador full-stack & creador creativo",
    paragraphOne: "Soy un desarrollador de productos full-stack que construye herramientas y apps para resolver problemas con los que me encuentro. Cuando algo resulta ser lo suficientemente bueno, lo comparto para que otros también puedan usarlo y, con suerte, les sea útil en su propio trabajo o vida diaria.",
    paragraphTwoPrefix: "Tengo más de 5 años de experiencia en desarrollo frontend y backend, trabajando con diversas tecnologías y frameworks. Me enfoco en construir experiencias de usuario performantes y hermosas, y disfruto crear cosas que se sientan rápidas y confiables. Actualmente trabajo en",
    paragraphTwoSuffix: "como Frontend Engineer, donde mi stack incluye React, Next.js, Tailwind y TypeScript.",
    paragraphThreePrefix: "Cuando no estoy programando, me encontrarás explorando nuevas tecnologías, yendo al gimnasio, jugando videojuegos o haciendo algo al aire libre. Puedes revisar",
    paragraphThreeMiddle: "los proyectos que he construido",
    paragraphThreeConnector: ", leer sobre mis experiencias y aprendizajes en",
    paragraphThreeSuffix: "o puedes contactarme en cualquier red social o vía correo.",
    paragraphThreeBlog: "mi blog",
  },
  projectsPage: {
    metaTitle: "Proyectos",
    metaDescription: "Cosas que he construido - apps, sitios web y experimentos.",
    heroTitle: "Mis proyectos",
    heroDescription: "Aquí están algunas de las cosas que he construido. Encontrarás apps, sitios web y experimentos con diferentes tecnologías y frameworks.",
  },
  blog: {
    metaTitle: "Blog",
    metaDescription: "Escribiendo sobre construcción de apps web, ingeniería de productos y las herramientas que lanzo.",
    heroTitle: "Blog",
    heroDescription: "Escribiendo sobre construcción de apps web, ingeniería de productos y las herramientas que lanzo.",
    emptyState: "Todavía trabajando en ello... Te mantendré informado.",
  },
  projectsData: {
    budio: {
      title: "Budio",
      description: "Planificador de presupuesto y rastreador de gastos para web y móvil.",
    },
    "r1go-dev": {
      title: "r1go.dev",
      description: "Sitio personal para mostrar proyectos y escribir sobre aprendizajes.",
    },
  },
} as const;

export default es;
